export const inputControlsArr=[
 {
    name:'que',
    lbl:'Quesiton',
    tag:'textarea',
    val:"",
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'opt1',
    lbl:'Option1',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'opt2',
    lbl:'Option2',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'opt3',
    lbl:'Option3',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'opt4',
    lbl:'Option4',
    tag:'input',
    type:'text',
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'type',
    lbl:'Type',
    tag:'input',
    type:'radio',
    options:['Single','Multiple'],
    values:['S','M'],
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 },
 {
    name:'ans',
    lbl:'Answer',
    tag:'select',
    options:['A','B','C','D','AB','AC','AD','BC','BD','CD','ABC','ACD','ABD','BCD','ABCD'],
    val:'',
    errorMsg:'',
    isShowErrorMsg:false
 }
]